=== MarkelAzpiazu23/RedCulinary/reto2.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" version="0.1">

<xs:element name="Clientes">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="cliente" maxOccurs="unbounded">
                <xs:complexType>
                        <xs:sequence>
                            <xs:element name="cliente_id">
                                <xs:simpleType>
                                    <xs:restriction base="xs:integer">
                                        <xs:totalDigits value="5"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="Nombre">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[A-Z][a-z]*"/>
                                        <xs:maxLength value="20"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="Apellidos">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[A-Z][a-z]*"/>
                                        <xs:maxLength value="30"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="Fecha_nacimiento" type="xs:date"/>
                            <xs:element name="Telefono" minOccurs="0" maxOccurs="2"/>
                            <xs:element name="Correo_electronico">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="Domicilio" type="xs:string"/>
                        </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:element>
</xs:schema>

=== MarkelAzpiazu23/RedCulinary/rero2XML.xml
<?xml version="1.0" encoding="utf-8"?>
<Clientes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="reto2.xsd">
    
    
    <cliente>
        <cliente_id>2</cliente_id>
        <Nombre>John</Nombre>
        <Apellidos>Doe</Apellidos>
        <Fecha_nacimiento>1990-05-15</Fecha_nacimiento>
        <Telefono>1234567890</Telefono>
        <Telefono>0987654321</Telefono> 
        <Correo_electronico>john.doe@example.com</Correo_electronico>
        <Domicilio>123 Main St, City, Country</Domicilio>
    </cliente>
    
    <cliente>
        <cliente_id>1</cliente_id>
        <Nombre>John</Nombre>
        <Apellidos>Doe</Apellidos>
        <Fecha_nacimiento>1990-05-15</Fecha_nacimiento>
        <Telefono>1234567890</Telefono>
        <Telefono>0987654321</Telefono> 
        <Correo_electronico>john.doe@example.com</Correo_electronico>
        <Domicilio>123 Main St, City, Country</Domicilio>
    </cliente>
</Clientes>
